site_name: n8n-lint Documentation
site_description: A Python-based CLI tool for validating JSON structures within n8n workflows
site_author: Dom Capparelli
site_url: https://capp3.github.io/n8n_lint

repo_name: capp3/n8n_lint
repo_url: https://github.com/capp3/n8n_lint

theme:
  name: readthedocs
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true

nav:
  - Home: index.md
  - User Guide:
      - Overview: user-guide/index.md
      - Installation: user-guide/installation.md
      - Basic Usage: user-guide/basic-usage.md
  - CLI Reference:
      - Overview: cli-reference/index.md
  - API Reference:
      - Overview: api-reference/index.md
  - Developer:
      - Overview: developer/index.md
      - Development Setup: developer/development-setup.md
  - Examples:
      - Sample Workflow: examples/sample_workflow.json
      - Workflow with Errors: examples/workflow_with_errors.json
      - Custom Node Schema: examples/custom_node_schema.json
  - Development:
      - Tasks: tasks.md
      - Status: status.md
  - Archive:
      - Overview: archive/README.md
      - Documentation Consolidation: archive/documentation-consolidation-20250910.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  # Temporarily disable emoji extension due to compatibility issues
  # - pymdownx.emoji:
  #     emoji_index: pymdownx.emoji.twemoji
  #     emoji_generator: pymdownx.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.arithmatex
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tilde
  - admonition
  - pymdownx.blocks.admonition
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.blocks.definition
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/capp3/n8n_lint
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/n8n-lint/
  version:
    provider: mike
