# Quick test workflow for pull requests
# Runs essential tests without full CI/CD pipeline

name: PR Test

on:
  pull_request:
    branches: [ "main", "develop" ]

permissions:
  contents: read

jobs:
  quick-test:
    name: Quick Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --all-groups

      - name: Run ruff linter
        run: uv run ruff check .

      - name: Run ruff formatter check
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest --tb=short -q

      - name: Run mypy type checker
        run: uv run mypy src/
